version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.6

    working_directory: ~/talkgenerator

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools
            python3 -m pip install -r requirements.txt
            python run_nltk_download.py

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools pytest-cov codecov
            pytest --cov=talkgenerator tests/
            codecov --token=e25ce249-b3da-4d80-b8d3-074f7d288969

      - store_artifacts:
          path: test-reports
          destination: test-reports
